#!/bin/zsh

mkdir gdb-build
mkdir gdb-install
cd gdb-build
../gdb-${V_GDB}/configure \
    --host=i686-w64-mingw32 \
    --prefix=/c/Users/Public/nano1804 \
    --program-prefix=aarch64-nano1804-linux-gnu- \
    --target=aarch64-linux-gnu \
    --with-sysroot=/c/Users/Public/nano1804/sys-root \
    --with-build-sysroot=/usr/local/nano1804-toolchain/sys-root \
    --enable-plugins \
    --disable-nls \
    --with-pkgversion="GDB for Jetson Nano 18.04" \
    --disable-nls \
    --with-expat \
    --with-libexpat-prefix=$PWD/../expat-install/usr/local/
# --with-python=$PWD/../makes/python-config-gdb
make -j4
DESTDIR=$PWD/../gdb-install make install
cd ../gdb-install
i686-w64-mingw32-strip --remove-section=.comment --remove-section=.note --strip-unneeded **/*.exe
