#!/bin/zsh

rm -rf tree-install
mkdir tree-install
rsync gcc-install/ tree-install -a --copy-links
rsync binutils-install/ tree-install -a --copy-links
rsync sysroot-install/ tree-install -a --copy-links
rsync gdb-install/ tree-install -a --copy-links
cd tree-install/c/Users/Public/bionic
du -hs .
i686-w64-mingw32-strip bin/*.exe
i686-w64-mingw32-strip aarch64-bionic*/bin/*.exe
find libexec -name \*.exe | xargs i686-w64-mingw32-strip
rm -rf share/info share/man

# Remove non prefixed gcc
rm bin/aarch64-linux-gnu-gcc*

pushd sys-root/usr/include
patch -p4 < ../../../../../../../../makes/case-sensitive-includes.diff
popd
rm -rf lib/xtables

du -hs .
