#!/bin/zsh

mkdir gdb-build
mkdir gdb-install
cd gdb-build
../gdb-${V_GDB}/configure \
    --program-prefix=arm-nano1804-linux-gnueabihf- \
    --target=aarch64-linux-gnu \
    --prefix=/usr/local/nano1804-toolchain \
    --with-pkgversion='GDB for Jetson Nano 18.04' \
    --disable-nls \
    --with-libexpat \
    --with-system-gdbinit=/usr/local/nano1804-toolchain/sys-root/usr/share/gdb/gdbinit \
    --with-sysroot=/usr/local/nano1804-toolchain/sys-root/ \
    --enable-lto \
    || exit $?
make || exit $?
DESTDIR=$PWD/../gdb-install make install|| exit $?
cd ../gdb-install
mkdir -p usr/local/nano1804-toolchain/sys-root/usr/share/gdb

