#!/bin/zsh

rm -rf tree-install
mkdir tree-install
rsync gcc-install/ tree-install -a --copy-links
rsync binutils-install/ tree-install -a --copy-links
rsync sysroot-install/ tree-install -a --copy-links
rsync gdb-install/ tree-install -a --copy-links
du -hs .

pushd tree-install
strip usr/local/bionic-toolchain/bin/*
strip usr/local/bionic-toolchain/aarch64-*/bin/*
find usr/local/bionic-toolchain/libexec -type f |xargs strip
# Remove non prefixed gcc
rm usr/local/bionic-toolchain/bin/aarch64-linux-gnu-gcc*
popd

du -hs .
